#!/bin/bash
find $(dirname $0)/log/ -type f -name GetStateIP.log -atime +1 -exec rm -f {} \;
HOSTS="192.168.210.2 192.168.210.30 192.168.210.8 192.168.210.254 192.168.210.3 192.168.210.4 192.168.210.5 192.168.210.6 192.168.210.7 192.168.210.9 192.168.210.10 192.168.210.11 www.google.com"
COUNT=1
IP=ifconfig | awk -F':' '/inet addr/&&!/127.0.0.1/{split($2,_," ");print _[1]}'
for myHost in $HOSTS
do
  myHostLog="$(dirname $0)/log/"$myHost".log"
  count=$(ping -c $COUNT $myHost | grep 'received' | awk -F',' '{ print $2 }' | awk '{ print $1 }')
  if [ $count -eq 0 ]; then
    # 100% failed 
    echo "Host : $myHost is down (ping failed) at $(date)" >> $(dirname $0)/log/GetStateIP.log
    if  [ ! -f $myHostLog ]; then
      curl "http://$IP/status.php?sonde=$myHost" 
      echo $(date) > $myHostLog
    fi
  else
    if [ -f $myHostLog ]; then
      rm -f $myHostLog
    fi
  fi
done
